name: laravel

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "5173:5173"
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    networks:
      - laravel-network

  webserver:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "7575:80"
    volumes:
      - ./www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
